"""
Profile routes - SECURE VERSION (CSRF + IDOR).

--------------------------------------------------------------------
WHY IS THIS SECURE (CSRF)?
--------------------------------------------------------------------
The email-change form (see app/templates/auth/profile.html) now
includes a hidden `csrf_token` field, and Flask-WTF's `CSRFProtect`
is initialized on the app (see app/__init__.py). Together these mean
every state-changing POST request - including the one handled by
update_email() below - must carry a valid, per-session CSRF token
generated by the server. A cross-origin attacker page can still get
the victim's browser to attach the session cookie automatically (that
part of the browser's behavior can't be changed), but it has no way
to read or forge the real token, since same-origin policy prevents it
from fetching the genuine /profile page's token. The forged request
is rejected before update_email() ever runs.

This directly fixes the vulnerability from the `vulnerable` branch,
where update_email() authenticated a request using ONLY the session
cookie, with no check that the request actually originated from this
application's own /profile page.

--------------------------------------------------------------------
WHY IS THIS SECURE (IDOR)?
--------------------------------------------------------------------
view_user() below additionally checks that the requested `user_id`
matches the logged-in user's own session id, and aborts with 403
otherwise - see the function for details.

--------------------------------------------------------------------
DEMONSTRATION
--------------------------------------------------------------------
See docs/testing/TC-CSRF-01.md and docs/testing/TC-IDOR-01.md for the
vulnerable-branch test scenarios these fixes defeat. The
proof-of-concept page at docs/testing/attacker_site/index.html, which
succeeds against the `vulnerable` branch, fails here because it has
no valid CSRF token to submit.
"""

from flask import Blueprint, abort, flash, redirect, render_template, request, session, url_for

from app.db import get_db

profile_bp = Blueprint("profile", __name__)


@profile_bp.route("/profile")
def profile():
    if "user_id" not in session:
        return redirect(url_for("auth.login"))

    db = get_db()
    user = db.execute(
        "SELECT id, username, email FROM users WHERE id = ?",
        (session["user_id"],),
    ).fetchone()
    return render_template("auth/profile.html", user=user)


@profile_bp.route("/profile/update", methods=["POST"])
def update_email():
    """
    SECURE: protected by Flask-WTF's CSRFProtect (see app/__init__.py)
    and the hidden csrf_token field in the email-change form (see
    app/templates/auth/profile.html). Any POST without a valid,
    matching CSRF token is rejected before this function body runs -
    the session-cookie check below is no longer the only defense.
    """
    if "user_id" not in session:
        return redirect(url_for("auth.login"))

    new_email = request.form.get("email", "").strip()
    if not new_email:
        flash("Email cannot be empty.")
        return redirect(url_for("profile.profile"))

    db = get_db()
    db.execute(
        "UPDATE users SET email = ? WHERE id = ?",
        (new_email, session["user_id"]),
    )
    db.commit()
    flash("Email updated successfully.")
    return redirect(url_for("profile.profile"))


@profile_bp.route("/users/<int:user_id>")
def view_user(user_id):
    if "user_id" not in session:
        return redirect(url_for("auth.login"))

    if user_id != session["user_id"]:
        abort(403)

    db = get_db()
    user = db.execute(
        "SELECT id, username, email, created_at FROM users WHERE id = ?",
        (user_id,),
    ).fetchone()

    if user is None:
        flash(f"No user found with id {user_id}.")
        return redirect(url_for("auth.dashboard"))

    is_own_profile = True
    return render_template("auth/view_user.html", user=user, is_own_profile=is_own_profile)
